### ISSUE TITLE
Apple rejection

### ISSUE THREAD

**Issue by dulgan** [Alterplay/APSmartStorage#2]
Hi,

I submitted an app using APSmartStorage to some some images and it appear that they weren't marked as "do not backup" so that it was too much data store in iCloud for Apple to accept the app...

Please update your code to include the possibility to store files in iCloud, but mark them by default as "do not backup" : 

NSURL *fileURL = [NSURL fileURLWithPath:path];
[fileURL setResourceValue:[NSNumber numberWithBool:YES]];

Thanks for your work anyway.

**Comment by belkevich** [comment]
Updated. Check version 1.0.4
