### ISSUE TITLE
Memory issue when using APSmartStorage downloading large image file

### ISSUE THREAD

**Issue by htaiwan** [Alterplay/APSmartStorage#3]
I am not sure it's an issue or not. Maybe I just use it incorrectly.
This is how I use APSmartStorage to download image.
It works fine if I download small images, but it crashed when downloading large image files(about 10~15 photos, size about 5M~10M).
Could I know how to fix it, thanks.

```
            APSmartStorage.sharedInstance().loadObjectWithURL(streamURL, storeInMemory: false, progress: { (progress: UInt) -> Void in
                }, completion: { (data:AnyObject!, url:NSURL! ,error: NSError!) -> Void in
                if error == nil {
                    let image = UIImage(data: data as! NSData)
                    fileImage.image = image
                    fileImage.contentMode = .ScaleToFill
                }
            })
```

**Comment by belkevich** [comment]
Hi!
Could you provide crashlog?

**Comment by htaiwan** [comment]
It's really strange of my crash log. I am not sure what the root cause is. 
But I know If I mark the code mentioned above, my app is fine
1. My crash log
![Image of Crashlog](http://i.imgur.com/jMRlm2j.png)
1. try to using instrument to find the memory issue
   ![Image of instrument1](http://i.imgur.com/m4F894P.png)
   ![Image of instrument2](http://i.imgur.com/ybMZ620.png)

Have you ever meet the issue before?

**Comment by belkevich** [comment]
Do you try to load same images without `APSmartStorage`?

**Comment by htaiwan** [comment]
yes... I try to use SDwebImage. It works fine.

**Comment by belkevich** [comment]
Do you really need such a big images in your app? May be you should resize it?
