### ISSUE TITLE
integration project

### ISSUE THREAD

**Issue by MarcSky** [Alterplay/APSmartStorage#4]
Hello everybody. I teach programming at ios two months. I need to learn how to cache the image server that the subsequent application was not loading download from the network.
I found your library but did not find her examples. I added to my project your .xcodeproj but can not figure out which library you want to import.
I put pictures in my cell of the table but first resize them as you can scale the image before insertion into the cell.
If not hard, do a small example of how to use the library in the example or tell me how to insert the image from the cache inside cellForRowAtIndexPath
And if not difficult, please tell me in what cases it is necessary to clean the cache memory or disk. Thank you for understanding.
![2015-09-26 16 47 36](https://cloud.githubusercontent.com/assets/4164003/10117845/58024e2a-646e-11e5-9b69-62662b91bdb8.png)

**Comment by belkevich** [comment]
Solved
