### ISSUE TITLE
ld: library not found for -lAPAsyncDictionary

### ISSUE THREAD

**Issue by Gleonidos** [Alterplay/APSmartStorage#5]
Привет, я нашел вас на гитхабе. Мне очень понравился ваш проект. Я новый разработчик iOS и поэтому мне трудно понять как работает ваша библиотека.
Скажите пожалуйста как ее для начала интегрировать в проект, я вставил в своей Podfile - pod 'APSmartStorage', '0.1.4' и сделал pod install. После чего мне вышло сообщение "The `Nation [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-Nation/Pods-Nation.debug.xcconfig'. This can lead to problems with the CocoaPods installation     - Use the`$(inherited)` flag, or     - Remove the build settings from the target."
Я вставил в OTHER_LDFLAGS флаг $(inherited). и мне вышла ошибка при компиляции
ld: library not found for -lAPAsyncDictionary

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Как быть((( Спасибо за помощь

Гогохия Леван
levangogohia@yandex.ru

**Comment by belkevich** [comment]
Разобрались в переписке
